# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 21:11
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='tagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagged', to='games.Participant'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=django_fsm.FSMField(choices=[('invited', 'Invited'), ('joined', 'Joined'), ('tagged', 'Tagged')], default='invited', max_length=50),
        ),
    ]
