# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 21:17
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0003_remove_participant_tagged_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='tagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagged', to=settings.AUTH_USER_MODEL),
        ),
    ]
