# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 06:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_participant_tagged_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=django_fsm.FSMField(choices=[('pending', 'Pending'), ('started', 'Started'), ('ended', 'Ended')], default='pending', max_length=50),
        ),
    ]
