# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coinbase_account_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
